version: "3"

services:
  elasticsearch:
    container_name: elasticsearch
    image: streetmeow/elasticsearch-nori:latest
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - TZ=Asia/Seoul
    user: root
    privileged: true

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    restart: always
    ports:
    - 5601:5601
    environment:
      - TZ=Asia/Seoul
    privileged: true
    depends_on:
      - elasticsearch

