version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    command:
    - --default-authentication-plugin=mysql_native_password
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - TZ=Asia/Seoul
    user: root
    privileged: true

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    restart: always
    ports:
    - 5601:5601
    environment:
      - TZ=Asia/Seoul
    privileged: true
    depends_on:
      - elasticsearch




